### ISSUE TITLE
[Feature request] Missing non-Linux/MacOS UNIX-entries

### ISSUE THREAD

**Issue by NitroNils** [Techno-Disaster/tldr-flutter#12]
No entries for common *BSD/illumos commands even though description claims "UNIX" coverage. The query "pkg" f.x. should return multiple hits across the BSDs. "pkgsrc" is even available on Linux/MacOS systems too. How to add such coverage?

**Comment by Techno-Disaster** [comment]
@NitroNils Thanks for submitting a issue about this, but I do see a couple of 'pkg..' suggestions in the app. Did not see pkgsrc though. FYI the data for the app comes from [tldr-pages](https://github.com/tldr-pages/tldr/tree/main/pages) so if its not there it won't show up in the app. Maybe create a issue there? 
cc: @bl-ue

**Comment by bl-ue** [comment]
Hi!  What's the problem exactly here?  I'm happy to help, but I'm not quite sure what @NitroNils is having  trouble with.  We don't have any `pkgsrc` command documented.  I don't have `pkgsrc` on my Mac either, or at least it's not in my `$PATH`.  A few more pointers?

**Comment by NitroNils** [comment]
@Techno-Disaster Ah, thsnk you for the pointer to tldr-pages - this is indeed where the issue lies.
My version is 1.1.0 and find no results with "pkg"- query.

**Comment by NitroNils** [comment]
@bl-ue The upstream project doesn't seem to include entries from other common open source Unix like operating systems (OpenSolaris- and BSD-based ones).

**Comment by Techno-Disaster** [comment]
Looks like this issue has been discussed in tldr pages, and should have been opened there. So I will close this for now.
