### ISSUE TITLE
[feature request] Offline mode

### ISSUE THREAD

**Issue by WaseemAlkurdi** [Techno-Disaster/tldr-flutter#13]
**Is your feature request related to a problem? Please describe.**
This app is amazing! However, tldr-flutter (at least the version from F-Droid) currently requires an internet connection, which is in stark contrast to the always-available offline `man` pages.
Wouldn't it be good if there was an option to download all pages, or at least cache/preload them?

**Describe the solution you'd like**
An option to download, cache or preload all available pages.

**Comment by Techno-Disaster** [comment]
> **Is your feature request related to a problem? Please describe.**
> This app is amazing! However, tldr-flutter (at least the version from F-Droid) currently requires an internet connection, which is in stark contrast to the always-available offline `man` pages.
> Wouldn't it be good if there was an option to download all pages, or at least cache/preload them?
> 
> **Describe the solution you'd like**
> An option to download, cache or preload all available pages.

Hey thanks for the review and creating a issue for this feature, yes it is possible to do this and is on my todo list. Hopefully I get the time to do this soon

**Comment by WaseemAlkurdi** [comment]
Been using this app for a while now - and thank you once more, @Techno-Disaster for a life-saver of an app! 😍
