### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by schwrzstrbn** [Techno-Disaster/tldr-flutter#14]
Make the scrolling experience smoother.

**Comment by Techno-Disaster** [comment]
> Make the scrolling experience smoother.

Which page are you experiencing stutter. Afaik all pages are built the same way so there should be no lag, atleast I don't see anything here. Where did you install the app from?

**Comment by schwrzstrbn** [comment]
from F-droid. then you need to optimize the app for the devices with low resources.

**Comment by Techno-Disaster** [comment]
> from F-droid. then you need to optimize the app for the devices with low resources.

Hmm looking into it.

**Comment by schwrzstrbn** [comment]
Thank you.

**Comment by Techno-Disaster** [comment]
@schwrzstrbn can you send your device specs? mode/cpu/ram ? I would like to try and test this on a similar level hardware emulator

**Comment by schwrzstrbn** [comment]
Realme C2, 2gb Ram, MediaTek Helio P2.

**Comment by Techno-Disaster** [comment]
@schwrzstrbn quick question is this better now? If so, please close this issue :D
