### ISSUE TITLE
search bar bug

### ISSUE THREAD

**Issue by schwrzstrbn** [Techno-Disaster/tldr-flutter#16]
Everytime I input text in the search bar the backspace button won't work.

**Comment by Techno-Disaster** [comment]
Android back button? Seems to work fine here. How do I reproduce it?

**Comment by schwrzstrbn** [comment]
Steps to reproduce/replicate:
1. Install from F-droid.
2. Open the installed tldr app.
3. Tap "Search" button.
4. input text and delete

Refer to the link for the screenshot.
-> https://ibb.co/qJhM4JF

**Comment by Techno-Disaster** [comment]
> Steps to reproduce/replicate:
> 
>     1. Install from F-droid.
> 
>     2. Open the installed tldr app.
> 
>     3. Tap "Search" button.
> 
>     4. input text and delete
> 
> 
> Refer to the link for the screenshot.
> -> https://ibb.co/qJhM4JF

Please attach the screenshot in the Github comment. The playstore version works fine so not sure why fdroid acts differently. I will upload a new build soon, maybe flutter has some fixes for it under the hood?

**Comment by Techno-Disaster** [comment]
@schwrzstrbn Can I close this as well? I have not been able to reproduce this till now.
