### ISSUE TITLE
Command Sorting by OS [w/ mockup]

### ISSUE THREAD

**Issue by gghhkm** [Techno-Disaster/tldr-flutter#20]
# A Quality of Life Feature
## - Sort the commands by OS in the "All Commands" menu.
![MockupWT](https://user-images.githubusercontent.com/72711094/137610402-e05f2741-f434-4c91-9a77-f197eee0039b.png)

<details>
<summary>Mockup w/o Text.</summary>
<br>

![Mockup](https://user-images.githubusercontent.com/72711094/137610586-a1cf2ed1-9a3d-4616-8f41-2250983dd445.png)
</details>

## Gimp Archive : 
[Mockup.zip](https://github.com/Techno-Disaster/tldr-flutter/files/7358708/Mockup.zip)

**Comment by gghhkm** [comment]
It's a little rough but I did what I could with the time I had.

**Comment by Techno-Disaster** [comment]
Thanks for the mockups, I have implemented somewhat similar design and should be on the play store and fdroid soon 

![image](https://user-images.githubusercontent.com/52817235/137646614-d8b2dcd4-d59a-4b2b-bd1f-ef38a337b504.png)

**Comment by gghhkm** [comment]
> AHHH, I lost my keystore so play console teams need 2 days to reset it, fdroid will probably be up before that so you can download from there or github releases

Amazing. tbh, like your version better.
