### ISSUE TITLE
Fail when running `flutter pub get`

### ISSUE THREAD

**Issue by blueskyson** [Techno-Disaster/tldr-flutter#23]
I don't have the experience of developing with flutter. Is there any way resolve the flutter version issue, or should I downgrade the flutter?

![Screenshot from 2021-10-21 17-02-55](https://user-images.githubusercontent.com/46962923/138254565-02ce91c1-b306-4527-8068-b1a8c87c61d6.png)

**Comment by Techno-Disaster** [comment]
> I don't have the experience of developing with flutter. Is there any way resolve the flutter version issue, or should I downgrade the flutter?
> 
> ![Screenshot from 2021-10-21 17-02-55](https://user-images.githubusercontent.com/46962923/138254565-02ce91c1-b306-4527-8068-b1a8c87c61d6.png)

I think you need to upgrade flutter, so `flutter upgrade` should do it.
