### ISSUE TITLE
My screen is blank

### ISSUE THREAD

**Issue by onkoe** [Techno-Disaster/tldr-flutter#24]
**Describe the bug**
My screen goes blank after about a second of runtime. Nothing helps this, even force quit. 

**To Reproduce**
1. Open the app
2. Go blind if it's night (optional) 

**Expected behavior**
The app should show.. the app. 

**Screenshots**
[Will a video suffice? ](https://imgur.com/gallery/MU8E2j5) 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: LineageOS 17.1
 - Browser: Tried with Firefox and Bromite (which is just Chromium) 
 - Version: 2.1.2

**Additional context**
Using the version from F-droid

**Comment by Techno-Disaster** [comment]
Ok I can confirm that this is a issue, somehow I was not able to catch this before. Working on it now

**Comment by onkoe** [comment]
Many thanks! :)

**Comment by Techno-Disaster** [comment]
Ok looks like transfer.sh went down and broke the whole app. It should be fixed in the new release https://github.com/Techno-Disaster/tldr-flutter/releases/tag/v2.2.0 can you give it a quick try?

**Comment by onkoe** [comment]
It's working well now! Thanks for the fix! Please feel free to close the issue :)
