### ISSUE TITLE
Command description buffering

### ISSUE THREAD

**Issue by tkameshgupta** [Techno-Disaster/tldr-flutter#25]
In android 11  after search command description is not loading it keep on buffering please help me thanks in advance

Please find the attached pic
![Screenshot_20211122-204854](https://user-images.githubusercontent.com/73092153/142887089-f5f75570-9728-40c3-b9c7-622ce66ec50f.png)

**Comment by Techno-Disaster** [comment]
Hey is this the latest version? Please update to the latest version from github releases. Fdroid and Playstore releases will come soon.

**Comment by tkameshgupta** [comment]
If I install offline apk version v8a from GitHub the problem is there.

**Comment by Techno-Disaster** [comment]
> If I install offline apk version v8a from GitHub the problem is there.

You need to install this https://github.com/Techno-Disaster/tldr-flutter/releases/tag/v2.2.0 apk. have internet on the first time you open the app. After that it will work even in offline mode

**Comment by tkameshgupta** [comment]
Thank you it is working
