### ISSUE TITLE
Add available languages

### ISSUE THREAD

**Issue by yutyo** [Techno-Disaster/tldr-flutter#27]
[tldr-pages](tldr.sh) repo has multiple languages available and new ones are added by contributors. I think it would be cool if this app had those optionally as well.

**Comment by Techno-Disaster** [comment]
@yutyo I have pretty much implemented this as good as I could, the design and code(this should be fixable in a couple of iterations) isn't the best IMO but it works as expected. Could you give it a test? (language can be changed in settings in drawer, and defaults to English when installed first)

The attached apks are built on https://github.com/Techno-Disaster/tldr-flutter/commit/36d82e7e4c05728bd31e60f0d4a7a9d1e35a084d commit. 
[release.zip](https://github.com/Techno-Disaster/tldr-flutter/files/7707612/release.zip)|


Any feedback would be appreciated. Thanks :D

**Comment by Techno-Disaster** [comment]
@yutyo quick question, did you give them a try? I would like to make a release then.

**Comment by yutyo** [comment]
> @yutyo quick question, did you give them a try? I would like to make a release then.

Yeah, its nice.

**Comment by Techno-Disaster** [comment]
> > @yutyo quick question, did you give them a try? I would like to make a release then.
> 
> Yeah, its nice.

Sounds good :D. Hopefully nothing really bad breaks. I'll make a new release asap.

**Comment by Techno-Disaster** [comment]
Released in latest releases. closing
