### ISSUE TITLE
[Feature Request] Fetch updates directly from the tldr-pages repository

### ISSUE THREAD

**Issue by vitorhcl** [techno-disaster/tldr-flutter#34]
**Is your feature request related to a problem? Please describe.**
The pages are not always updated.

**Describe the solution you'd like**
Fetch the pages directly from the tldr pages-repository or download the pages ZIP.

**Comment by techno-disaster** [comment]
These should get automatically updated the next day. Could be better but td is unable to rewrite it atm.
