### ISSUE TITLE
app title in recents menu - "Flutter Demo"

### ISSUE THREAD

**Issue by locness3** [Techno-Disaster/tldr-flutter#4]
![Screenshot_20210331-170416](https://user-images.githubusercontent.com/37651007/113166626-3c79a000-9243-11eb-93db-82555ac09aae.png)

**Comment by Techno-Disaster** [comment]
Ah thanks for the issue, looks like I forgot to edit the name [here](https://github.com/Techno-Disaster/tldr-flutter/blob/857305297f98414211cc4f490f805cc61b711123/lib/main.dart#L33)

**Comment by bl-ue** [comment]
@Techno-Disaster see #5
