### ISSUE TITLE
Wrong versionCode/Name for version 1.1.0

### ISSUE THREAD

**Issue by jspricke** [Techno-Disaster/tldr-flutter#7]
https://github.com/Techno-Disaster/tldr-flutter/blob/54faf59b23ea79a510150815ed9a95a5d121d6ef/android/app/build.gradle#L16-L21

This breaks the F-Droid build, please fix them and tag a new version.

**Comment by Techno-Disaster** [comment]
@jspricke It should pickup the version name and code from the [pubspec.yaml](https://github.com/Techno-Disaster/tldr-flutter/blob/master/pubspec.yaml), but I released the tag first and then pushed the version code and name commit. So to start a new build all you need is a new tag right?

**Comment by jspricke** [comment]
Please don't rewrite git tags as they are not updated by a git pull. Simply make a new release, there are enough numbers left ;).

**Comment by Techno-Disaster** [comment]
Published v1.1.0 hopefully that fixes stuff

**Comment by Techno-Disaster** [comment]
@jspricke looks like the new version is still not up on f-droid, iirc there was some page where I could see the build logs but can't find it now. Could you link me to it to check if there is any error?

**Comment by jspricke** [comment]
it was not picked up cause the latest version (1.1.0) was already tried and the new tag did not match the version. I fixed it manually: https://gitlab.com/fdroid/fdroiddata/-/commit/627a9291aef72f0be60356cb46092810bc36c1d6

**Comment by Techno-Disaster** [comment]
> it was not picked up cause the latest version (1.1.0) was already tried and the new tag did not match the version. I fixed it manually: https://gitlab.com/fdroid/fdroiddata/-/commit/627a9291aef72f0be60356cb46092810bc36c1d6

Makes sense, thanks for the help. Will keep in mind when publishing the next update.
